
import { Web3Storage } from 'web3.storage'
import apiKey from "../config/apiKey"
// what the json should be like
// {
//     "name": "cyberBAYC",
//     "description": "young bayc test",
//     "image": " ipfs://bafybeia5cq5sbd5vunezcb5sun5b7tj4nfwdzymaohy352pwsoqtv3iysm/bayc",
//     "attributes": [    {
//         "trait_type": "young", 
//         "value": "good"
//       }]
//   }

const FILENAME =  "test.json";

function getAccessToken () {
    return apiKey["WEB3STORAGE_TOKEN"];
}

function makeStorageClient () {
    return new Web3Storage({ token: getAccessToken() })
}

function makeFileObjects (projName,userAddr,amount,totalAmount) {
    // You can create File objects from a Blob of binary data
    // see: https://developer.mozilla.org/en-US/docs/Web/API/Blob
    // Here we're just storing a JSON object, but you can store images,
    // audio, or whatever you want!
    const obj = { 
        name : projName+" Donation Certificate",
        description : "The cert was generated by user "+userAddr +" to memorize the donation made to project "+projName,
        image : "ipfs://bafybeiekqloms77qy6aix3tontmuvbbl3iaijekxnrlfxju5xshrzijbse/certificate.jpg",
        "attributes": [    
          {
            "trait_type": "whale", 
            "value": amount * 10 >= totalAmount ? "yes" : "no"
          },
          {
            "trait_type": "amount", 
            "value": amount
          }
        ]
    }

    console.log(obj);

    const blob = new Blob([JSON.stringify(obj)], { type: 'application/json' })
  
    return [new File([blob], FILENAME)];
}

async function storeFiles (files) {
    const client = makeStorageClient()
    const cid = await client.put(files)
    console.log('stored files with cid:', cid);
    return cid
  }

export default async function tokenURL(projName,userAddr,amount,totalAmount) {
    const cid = await storeFiles(makeFileObjects(projName,userAddr,amount,totalAmount));
    const tokenURL = "ipfs://"+cid+"/"+FILENAME;
    console.log(tokenURL);
    return tokenURL;
}